### ISSUE TITLE
Download registered as completed, but hash check returned unfinished chunks.

### ISSUE THREAD

**Issue by terrorindeed** [Bercik1337/rt-auto-install#38] opened 2023-02-27 18:41 UTC
I've rebuilt my VM, I no longer get any request timeout errors. I am still using google drive mounted with rclone as my download directory.
But I'm curious why, after I complete sudo shutdown. And then restart the VM, I have dozens of Error torrents. 
I started small to see how this would work. I added 92 torrents, 5.19TiB. Waited for them all to recheck, complete 100% and begin seeding. Shutdown the VM, restarted the VM. 
61 remained completed, 31 errored-Pausing "Download registered as completed, but hash check returned unfinished chunks" and are at 0%, force recheck resumes and begins checking. 

Thanks

**Comment by terrorindeed** [comment] 2023-02-28 05:18
I may have fixed the issue. I read a forum post from 2011 with a similiar problem when restarting rtorrent.service. I stopped all 93 torrents after they had completed and were seeding. The torrents were marked as Finished 100%. 
I ran
sudo systemctl stop rtorrent.service
sudo shutdown

Then started the VM again. To my delight all 92 torrents were still 100% Finished. 
I then ran a backup of my VM, and restored from the VM, again, all torrents were 100% Finished. Hopefully this helps someone else out.
Thannks

**Comment by Bercik1337** [comment] 2023-03-03 11:49
@terrorindeed please paste the /etc/systemd/system/rtorrent.service content.
it seems that when you shutdown the system - it doesn't gracefully stop the rtorrent, instead it gets killed. That's the reason for rehash problem.

**Comment by terrorindeed** [comment] 2023-03-03 17:03
[Unit]
Description=rtorrent (in tmux)

[Service]
Type=forking
RemainAfterExit=yes
User=tcd
ExecStart=/usr/bin/tmux -2 new-session -d -s rtorrent rtorrent
ExecStop=/usr/bin/tmux send-keys -t rtorrent:rtorrent C-q
RemainAfterExit=no
Restart=on-failure
RestartSec=5s
[Install]
WantedBy=default.target

**Comment by terrorindeed** [comment] 2023-03-03 17:03
I made no edits to this after a fresh ubuntu 22.04.1 LTS install.

**Comment by Bercik1337** [comment] 2023-03-03 19:24
@terrorindeed try changng this file into:
```
	[Unit]
	Description=rtorrent (in tmux)

	[Service]
	Type=forking
	RemainAfterExit=yes
	User=$RTORRENT_USER
	ExecStart=/usr/bin/tmux -2 new-session -d -s rtorrent rtorrent
	ExecStop=/usr/bin/tmux send-keys -t rtorrent:rtorrent C-q
	RemainAfterExit=no
	Restart=on-failure
	RestartSec=60s
	TimeoutStopSec=360
	[Install]
	WantedBy=default.target
```

and then do
`sudo systemctl daemon-reload`

and see if you can reproduce the same problem (or maybe you don't want to waste more time on it, i don't know)

this change should tell system to wait 6minutes before completely killing rtorrent program when you stop service or reboot system. I can't repro your problem because all my tracker respond very fast. But this should help to prevent killing rtorrent service and losing metadata file is already downloaded etc.

:crossed_fingers:  let me know.

**Comment by Bercik1337** [comment] 2023-04-03 10:17
No info. Closing.

**Closed by Bercik1337** 2023-04-03 10:17 UTC
