### ISSUE TITLE
Uninstall script / permissions issue

### ISSUE THREAD

**Issue by yotoprules** [Bercik1337/rt-auto-install#13] opened 2021-08-11 18:59 UTC
Hi,
I installed this script, and it half-worked, but permissions were not assigned correctly, so I can't change any settings in the web ui, can't add any torrents, plugins aren't working, etc, and I can't figure out how to fix this manually.
If possible I would like this to be fixed, plus an uninstall script would be handy. 
I uninstalled "rtorrent" and "apache2" but there is probably more stuff lingering from the script.

Thanks :)

**Comment by Bercik1337** [comment] 2021-08-14 06:35
Hey, what exactly do you mean by "half worked"?  No one ever reported problem. Did you use it on FRESH installation of the system?
Only files created are .rtorrent.rc in $HOME and apache config in /etc

**Comment by yotoprules** [comment] 2021-08-14 13:08
No it isn't a fresh install, I have other stuff on it, SSH, SFTP, Jellyfin, and other torrent clients.

By half working, I mean it installed, I can load rutorrent, but it won't load any of the plugins, I can't browse the filesystem or add any torrents, and changing any settings in the rutorrent WEB UI are not retained after restarting.

**Comment by Bercik1337** [comment] 2021-08-14 16:31
Please try to run this in freshly installed VM and let me know if it works fine there.

**Comment by yotoprules** [comment] 2021-08-19 20:47
OK, I made a clean install of Lubuntu 21.04, updated it, then ran the script, rutorrent loads but I get these errors:
[https://i.ibb.co/MB9G94y/image.png](url)
and as you can see I cannot browse the filesystem via rutorrent, and any settings made in the rutorrent UI are not saved.

**Comment by Bercik1337** [comment] 2021-08-20 21:37
Hey again
I tested quickly in 2 VMs and i confirm, there is a problem. They must've changed some package in repository because it didn't happen before.

I will look into it next week-ish (hopefully because I'm very busy)

**Comment by Bercik1337** [comment] 2021-08-21 11:10
@yotoprules i got good news and bad news
NEWS
1. GOOD - found the problem. it's permissions on HOME folder in Lubuntu. This is not script fault.
2. BAD - I checked once more all other versions (ubuntus, different versions). It is ONLY Lubuntu that has different permissions. Script supports Ubuntu, not it's clones.  I'm aware that Lubuntu/Xubuntu and others are clones of Ubuntu, but as you can see - not 1:1 copy. 

SOLUTION
1. EASY - all you have to do really is grant read and execute permissions on your home folder. Issue command `chmod o+rx $HOME`
2. If you are planning to have more than one user, you can modify root cause of this problem. Lubuntu configuration of default user permissions on home folders: `/etc/login.defs` in line `HOME_MODE`

BONUS
Justy FYU, Ubuntu 21.04 reached EOL recently, that means it's no longer supported. I would recommend to either upgrade to newer OR go back to previous LTS version.

I'm not closing the issue yet in case you want to reply (for a week).

Have a great day.

**Closed** 2021-09-03 17:14 UTC
